apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
  annotations:
spec:
  advanced:
    retentionConfig:
      blockDuration: 3h
      cleanupInterval: 6m
      deleteDelay: 50h
      retentionInLocal: 5d
      retentionResolution1h: 31d
      retentionResolution5m: 15d
      retentionResolutionRaw: 6d
  nodeSelector:
    kubernetes.io/os: linux
  observabilityAddonSpec:
    enableMetrics: true
    interval: 30
    resources:
      limits:
        cpu: 200m
        memory: 700Mi
      requests:
        cpu: 200m
        memory: 200Mi
  storageConfig:
    alertmanagerStorageSize: 1Gi
    compactStorageSize: 1Gi
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
    receiveStorageSize: 1Gi
    ruleStorageSize: 1Gi
    storageClass: gp2
    storeStorageSize: 1Gi
