apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
  annotations:
spec:
  nodeSelector:
    kubernetes.io/os: linux
  observabilityAddonSpec: {}
  retentionConfig: {}
  storageConfig:
    alertmanagerStorageSize: 1Gi
    compactStorageSize: 4Gi
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
    receiveStorageSize: 4Gi
    ruleStorageSize: 1Gi
    storageClass: gp2
    storeStorageSize: 1Gi
