apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  enableDownsampling: false
  imagePullPolicy: Always
  imagePullSecret: multiclusterhub-operator-pull-secret
  nodeSelector:
    kubernetes.io/os: linux
  observabilityAddonSpec:
    enableMetrics: true
    interval: 30
    resources:
      limits:
        cpu: 100m
        memory: 600Mi
      requests:
        cpu: 100m
        memory: 100Mi
  retentionConfig:
    blockDuration: 2h
    cleanupInterval: 5m
    deleteDelay: 48h
    retentionInLocal: 4d
    retentionResolution1h: 30d
    retentionResolution5m: 14d
    retentionResolutionRaw: 5d
  storageConfig:
    alertmanagerStorageSize: 1Gi
    compactStorageSize: 1Gi
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
    receiveStorageSize: 1Gi
    ruleStorageSize: 1Gi
    storageClass: gp2
    storeStorageSize: 1Gi
