apiVersion: observability.open-cluster-management.io/v1beta1
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  nodeSelector:
    kubernetes.io/os: linux
  observabilityAddonSpec: {}
  retentionResolutionRaw: 5d
  retentionResolution5m: 14d
  retentionResolution1h: 30d
  storageConfigObject:
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
    statefulSetStorageClass: gp2
