apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  annotations:
    mco-imageTagSuffix:
    mco-thanos-without-resources-requests: "true"
  name: observability
spec:
  nodeSelector:
    kubernetes.io/os: linux
  observabilityAddonSpec: {}
  retentionConfig: {}
  storageConfig:
    alertmanagerStorageSize: 1Gi
    compactStorageSize: 2Gi
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
    receiveStorageSize: 2Gi
    ruleStorageSize: 1Gi
    storageClass: standard
    storeStorageSize: 1Gi

